### ISSUE TITLE
Modal behaviour of the contour plots

### ISSUE THREAD

**Issue by bnlawrence** [ajheaps/cf-view#4]
Can we make it non-blocking?

**Comment by ajheaps** [comment]
cf-plot 1.9.22 addresses this by using the ImageMagick display command, if it is available, to display the plots in a subprocess call.  If display isn't available then the built-in Matplotlib viewer is used to display plots.  I'll put a menu item in so that users can switch between the two modes for those who want more control.  
I cannot do a conda upload today as there looks to be an issue with PyQt4 which is used as a matplotlib background.  I'll report this and do a new conda release of cf-plot as soon as I can. cf-plot is also available from GitHub and pypi.
